### ISSUE TITLE
Adding/removing controls/layers with += and -=

### ISSUE THREAD

**Issue by deeplook** [heremaps/here-map-widget-for-jupyter#4]
I can add controls and layers only with `map.add_control()` and `add_layer()` but I would also like to use `+=` on the map as this shortens the code considerably when putting many things onto the map. In Ipyleaflet this is perfectly possible. It would be nice to have it here, too (no pun intended).

```python
import os
from here_map_widget import Map, DefaultLayers, DefaultLayerNames, ZoomControl

api_key = os.getenv("HEREMAPS_API_KEY")
basemap = DefaultLayers(layer_name=DefaultLayerNames.raster.normal.map)
m = Map(center=[52, 13], zoom=6, basemap=basemap, api_key=api_key) 
m.add_control(ZoomControl(alignment="LEFT_TOP"))  # preferred: m += ZoomControl(...)
```

**Comment by sackh** [comment]
resolved in #5

**Comment by deeplook** [comment]
I still get this for a newly installed version 1.0.0.

<img width="891" alt="Screenshot 2021-03-01 at 10 12 13" src="https://user-images.githubusercontent.com/1001778/109476217-ee705180-7a76-11eb-84ed-a491d22ab2a9.png">

**Comment by sackh** [comment]
This change is not part of 1.0.0. Please check the changelog.
